# @pastex file: radiophonicus.toml
# @pastex target: ~/src/bombadil/.dots/radiophonicus.toml
# @pastex version: 1.2.0
# @pastex change: Bombadil template using cross-profile variables.

[paths]
# Dynamically injected by Bombadil
default_output = "{{ playlist_dir }}/last_gen.m3u8"
vlc_db_path = "{{ vlc_db_path }}"

[sorting]
default_sort = "album,track,date"